# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        image: nginx:1.21.5-alpine
        ports:
            - 80:80
        networks:
            sail:
                ipv4_address: 172.27.0.2
        environment:
            host_url: "${APP_URL}"
        volumes:
            - ./Dockerfiles/nginx.dev.conf:/etc/nginx/nginx.conf
            - ./nginx.log:/var/log/nginx/error/error.log
        container_name: myweb-proxy
networks:
    sail:
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/16
    out-network:
        driver: bridge
